### PR TITLE
Add install instructions for Vundle

### PR DESCRIPTION
**Pull request by IanVaughan**

### CODE REVIEW

**Comment by rogererens** [comment]
See #33

**Comment by AdrienLemaire** [comment]
Are you sure that's all that is needed to get vim-colors-solarized work with Vundle?

Because my vim colors are not properly solarized:

screenshot

And I can't really figure out why

**Comment by AdrienLemaire** [comment]
Hmm I somehow fixed it. Probably setting `let g:solarized_termcolors=16` (was 256 before).

Got a weird issue, that the themes are inversed (`background=light` gives the dark theme and vice-versa), but doesn't really matter as I handle it in scripts.

**Comment by IanVaughan** [comment]
Guess not going to be merged ;-)

**Pull request closed without merging**
